### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [seoojunn/PY202309#1]
### 없는 파일
- project/week8/search_engine.ipynb
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 없는 PDF 파일
- project/week8/search_engine.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 에러 있음. 아래 파일/에러메세지/솔루션을 확인하세요
- ERROR in challenge/week7/todo
    - invalid syntax (<unknown>, line 52)
        -  break 반복문 탈출 <- 해당 코드로 인해 코드가 실행되지 않습니다. 주석 처리를 정확히 해주세요.

**Comment by seoojunn** [comment]
serch_engine.ipynb -> search_engine.ipynb로 수정
serch_engine.pdf -> search_engine.pdf로 수정
주석 처리 후 커밋하였습니다.
